# Generated by Django 5.0 on 2024-11-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('guests', models.IntegerField()),
                ('income', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='app.section'),
        ),
    ]
