# Generated by Django 5.0 on 2024-10-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('isEnable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.restaurant'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('dishes', models.ManyToManyField(blank=True, to='app.dish')),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.menu')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='app.section'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, default='worker.png', null=True, upload_to='avatar/%Y/%M/%D')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worjers', to='app.profession')),
            ],
        ),
    ]
