# Generated by Django 5.0 on 2024-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_revenue_alter_dish_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='profit',
            field=models.IntegerField(null=True),
        ),
    ]
