# Generated by Django 5.0 on 2024-11-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_revenue_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='background.webp', null=True, upload_to='restaurant_image/%Y/%M/%D'),
        ),
    ]
