# Generated by Django 5.0 on 2024-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_date_alter_dish_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('guests', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
