# Generated by Django 5.0 on 2024-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
