# Generated by Django 5.0 on 2024-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_restaurant_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='content',
            field=models.TextField(default='', max_length=200),
        ),
    ]
