# Generated by Django 5.0 on 2024-11-12 14:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservation_comment_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='89247777777', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?[7,8]?[\\s,-]?\\(?\\d{3}\\)?[\\s,-]?\\d{3}[\\s,-]?\\d{2}[\\s,-]?\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?[7,8]?[\\s,-]?\\(?\\d{3}\\)?[\\s,-]?\\d{3}[\\s,-]?\\d{2}[\\s,-]?\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 12)),
        ),
    ]
