# Generated by Django 5.0 on 2024-11-12 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_reservation_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format', regex='^\\+?[7,8]?[\\s,-]?\\(?\\d{3}\\)?[\\s,-]?\\d{3}[\\s,-]?\\d{2}[\\s,-]?\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
