# Generated by Django 5.0 on 2024-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reservation_phone_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verdict',
            field=models.CharField(choices=[(1, 'Удивительно!'), (2, 'Хорошо!'), (3, 'Плохо!'), (4, 'Ужасно!')], max_length=15),
        ),
    ]
