# Generated by Django 5.0 on 2024-11-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orderdish_order_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='app.order'),
        ),
    ]
