# Generated by Django 5.0 on 2024-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_review_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
