# Generated by Django 5.0 on 2024-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_time_remove_review_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('Официант', 'Официант'), ('Повар', 'Повар'), ('Менеджер', 'Менеджер')], default='', max_length=10),
        ),
    ]
