# Generated by Django 5.0 on 2024-11-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_worker_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('Официанты', 'Официанты'), ('Повара', 'Повара'), ('Менеджеры', 'Менеджеры')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profession',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='app.restaurant'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profession',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.profession'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(max_length=6),
        ),
    ]
