# Generated by Django 5.0 on 2024-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profession_name_alter_profession_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='isEnable',
        ),
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, default='dish.webp', null=True, upload_to='dish_image/%Y/%M/%D'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('Комбо', 'Комбо'), ('Закуски', 'Закуски'), ('Супы', 'Супы')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
