# Generated by Django 5.0 on 2024-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_profile_profile_user_alter_review_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile',
        ),
    ]
